AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template implements an IAM user 'Bob'
  And permissions appropriate for Bob.
Parameters:
  bobpassword:
    NoEcho: true
    Description: IAM User bob Password.
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$
    ConstraintDescription: Password must be a minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character.
Resources:
  bob:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMUserChangePassword
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref policy
      LoginProfile:
        Password: !Ref bobpassword
        PasswordResetRequired: "false"
  policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow access to all S3 buckets and RoleAssume
      ManagedPolicyName: S3AndRoleAssume
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "s3:*"
            Resource: "*"
          - Effect: Allow
            Action: "sts:AssumeRole"
            Resource: "*"
